categories: 
- Sequence Analysis
description: Resistance Gene Identifier (RGI) predicts resistome(s) from protein or nucleotide data based on homology and SNP models
long_description: This tool provides a preliminary annotation of your DNA sequence(s) based upon the data available in CARD. Hits to genes tagged with Antibiotic Resistance ontology terms will be highlighted. As CARD expands to include more pathogens, genomes, plasmids, and ontology terms this tool will grow increasingly powerful in providing first-pass detection of antibiotic resistance associated genes.
name: rgi
owner: card
remote_repository_url: https://github.com/arpcard/rgi
type: unrestricted
