name: Autobuild

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-planemo-0.70.0
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel 'planemo==0.70.0'
    - name: planemo shed_update
      env: 
        SHED_KEY: ${{ secrets.SHED_KEY }}
      run: planemo shed_update -r -t toolshed --check_diff --force_repository_creation --shed_key_from_env SHED_KEY
